# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS := my-xdp-firewall.bpf
TOOL_NAME := my-xdp-firewall-loader
USER_TARGETS := my-xdp-firewall-loader

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
